apiVersion: config.sdcio.dev/v1alpha1
kind: Config
metadata:
  name: srl-spine
  namespace: default
  labels:
    config.sdcio.dev/targetName: srl-spine
    config.sdcio.dev/targetNamespace: default
spec:
  priority: 10
  config:
  - path: /
    value:
      interface:
      - admin-state: enable
        description: leaf1:et-1/1.0
        name: ethernet-1/1
        subinterface:
        - admin-state: enable
          index: 0
          ipv4:
            address:
            - ip-prefix: 192.168.0.2/31
            admin-state: enable
            unnumbered:
              admin-state: disable
      - admin-state: enable
        description: leaf2:et-1/1.0
        name: ethernet-1/2
        subinterface:
        - admin-state: enable
          index: 0
          ipv4:
            address:
            - ip-prefix: 192.168.0.4/31
            admin-state: enable
            unnumbered:
              admin-state: disable
      - admin-state: enable
        name: mgmt0
        subinterface:
        - admin-state: enable
          index: 0
          ipv4:
            admin-state: enable
            dhcp-client: {}
          ipv6:
            admin-state: enable
            dhcp-client: {}
      - admin-state: enable
        description: Loopback
        name: system0
        subinterface:
        - admin-state: enable
          index: 0
          ipv4:
            address:
            - ip-prefix: 172.16.0.10/32
            admin-state: enable
            unnumbered:
              admin-state: disable
      network-instance:
      - admin-state: enable
        description: Default VRF
        interface:
        - name: ethernet-1/1.0
        - name: ethernet-1/2.0
        - name: system0.0
        name: default
        protocols:
          bgp:
            afi-safi:
            - admin-state: enable
              afi-safi-name: ipv4-unicast
            autonomous-system: 64512
            group:
            - afi-safi:
              - admin-state: enable
                afi-safi-name: evpn
              - admin-state: disable
                afi-safi-name: ipv4-unicast
              export-policy: all
              group-name: IBGP-OVERLAY
              import-policy: all
              peer-as: 64512
              route-reflector:
                client: true
              timers:
                minimum-advertisement-interval: 1
            neighbor:
            - peer-address: 172.16.0.11
              peer-group: IBGP-OVERLAY
              transport:
                local-address: 172.16.0.10
            - peer-address: 172.16.0.12
              peer-group: IBGP-OVERLAY
              transport:
                local-address: 172.16.0.10
            router-id: 172.16.0.10
          isis:
            instance:
            - admin-state: enable
              name: ISIS
              net:
              - 49.0001.0000.0000.0010.00
